add Common Function Pool sdk
nttcom/eclcloud pull request #31
Opened 2021-02-17 07:26 UTC by karasuex54

This Pull Request does follwoings.

- Add Common Function Pool sdk.
- Add unit test of the above.

2021-02-17 11:22 UTC, ysssasaki requested changes
2点コメントしました  :bow:

2021-02-17 11:22 UTC, ysssasaki commented on ecl/network/v2/common_function_pool/requests.go
> +// `asc' or `desc'. Marker and Limit are used for pagination.
このコメントはListOptsの説明になっています。
これをListOptsBuilderの説明に変更し、また次のListOptsに説明を加えてください。

2021-02-17 11:22 UTC, ysssasaki commented on ecl/network/v2/common_function_pool/urls.go
> +}
commmon_function_pool APIにCUDは存在しないので不要です。

2021-02-18 07:18 UTC, NaoShark requested changes
コメントしました。

2021-02-18 07:18 UTC, NaoShark commented on ecl/network/v2/common_function_pool/doc.go
> +package common_function_pool
IDFromName の Example も追加していただいてよろしいでしょうか？

2021-02-18 07:18 UTC, karasuex54 commented
Fix typo and unused function

2021-02-18 07:47 UTC, karasuex54 commented
Add example and format code

2021-02-18 07:59 UTC, NaoShark approved these changes
LGTM.

2021-02-18 08:02 UTC, ysssasaki approved these changes
LGTM 🍊

2021-02-18 08:05 UTC, merged