✨ Switchover SSS v2 API, Support Workspace CRUD
nttcom/eclcloud pull request #40
Opened 2022-05-19 09:17 UTC by shimisho

eclcloud の sss 関連リソースで実行する API のバージョンを v1.0 から v2 に切り替えました。
それに伴うコードの変更と新規追加となる Workspace 関連リソースのCRUDの関数を追加しました。
今回のアップデートはメジャーバージョンアップとなるので以下のページの作業内容を参考にファイルを更新しています。
https://nttcom.atlassian.net/wiki/spaces/IF/pages/2275246420/Version+2+eclcloud

2022-05-23 03:04 UTC, NaoShark requested changes

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/tenants/doc.go
> +Package projects manages and retrieves Projects in the ECL SSS Service.
```suggestion
Package tenants manages and retrieves Projects in the ECL SSS Service.
```

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/users/doc.go
> +package users
example の記載をお願いします。

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/workspace_roles/doc.go
> +package workspace_roles
example の記載をお願いします。

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/workspaces/doc.go
> +package workspaces
example の記載をお願いします。

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/approval_requests/testing/fixtures.go
> +			Text: "approval resquest test",
```suggestion
			Text: "approval request test",
```

2022-05-23 03:04 UTC, naoshark commented on v3/ecl/sss/v2/approval_requests/testing/fixtures.go
> +			Text: "approval resquest test",
```suggestion
			Text: "approval request test",
```

2022-05-23 03:04 UTC, NaoShark commented on v3/ecl/sss/v2/users/results.go
> +	StartTime              time.Time `json:"-"`
https://sdpf.ntt.com/docs/about-sss/api-references/rsts/APIList/v2/User/GetUser.html と一致してなさそうなのですが確認お願いしてもよろしいでしょうか？

2022-05-23 03:04 UTC, NaoShark commented on v3/ecl/sss/v2/approval_requests/requests.go
> +// ToResourceUpdateCreateMap formats a UpdateOpts to update approval request.
```suggestion
// ToResourceUpdateMap formats a UpdateOpts to update approval request.
```

2022-05-23 03:04 UTC, NaoShark commented on v3/ecl/sss/v2/tenants/results.go
> +	// TenantRegion the tenant blongs.
```suggestion
	// TenantRegion the tenant belongs.
```

2022-05-23 03:04 UTC, NaoShark commented on v3/ecl/sss/v2/tenants/results.go
> +	// In "show(get with ID of tennat)" case, this does not occur.
```suggestion
	// In "show(get with ID of tenant)" case, this does not occur.
```

2022-05-23 03:04 UTC, NaoShark commented on v3/ecl/sss/v2/users/urls.go
> +func getURL(client *eclcloud.ServiceClient, tenantID string) string {
```suggestion
func getURL(client *eclcloud.ServiceClient, userID string) string {
```
同一ファイルの他箇所にも適用お願いします。

2022-05-23 05:46 UTC, shimisho commented on v3/ecl/sss/v2/users/results.go
> +	StartTime              time.Time `json:"-"`
当初 [SSSのリファレンス](https://nttcom.atlassian.net/wiki/spaces/SSS/pages/370344952/01.Users+API#id-01.UsersAPI-%E3%83%A6%E3%83%BC%E3%82%B6%E6%83%85%E5%A0%B1%E5%8F%96%E5%BE%97) からレスポンスの構造体を作成したのですが、admin role でしか返却されない項目なども含まれていました。
提示くださったリファレンスの方が実際のレスポンスに忠実なのでそちらを参考に修正しました。

2022-05-24 23:22 UTC, NaoShark requested changes

2022-05-24 23:22 UTC, NaoShark commented on v3/ecl/sss/v2/tenants/doc.go
> +	allProjects, err := tenants.ExtractProjects(allPages)
```suggestion
	allTenants, err := tenants.ExtractProjects(allPages)
```

2022-05-24 23:22 UTC, NaoShark commented on v3/ecl/sss/v2/users/doc.go
> +	}
```suggestion
	allUsers, err := users.ExtractUsers(allPages)
	if err != nil {
		panic(err)
	}

	for _, user := range allUsers {
		fmt.Printf("%+v\n", user)
	}
```

2022-05-24 23:22 UTC, NaoShark commented on v3/ecl/sss/v2/workspaces/doc.go
> +	}
```suggestion
	allWorkspaces, err := workspaces.ExtractWorkspaces(allPages)
	if err != nil {
		panic(err)
	}

	for _, workspace := range allWorkspaces {
		fmt.Printf("%+v\n", workspace)
	}
```

2022-05-25 02:14 UTC, NaoShark approved these changes

2022-05-25 03:10 UTC, ysssasaki requested changes

2022-05-25 03:10 UTC, ysssasaki commented on v3/ecl/sss/v2/tenants/results.go
> +type Tenant struct {
元々の不具合で申し訳ありませんが、regionやuserの情報が抜けているように見えます
https://sdpf.ntt.com/docs/about-sss/api-references/rsts/APIList/v1/Tenant/GetTenant.html

2022-05-25 06:11 UTC, shimisho commented on v3/ecl/sss/v2/tenants/results.go
> +type Tenant struct {
region_api_endpoint, users, brand_id の情報を取得するようにしました。
region の値は 元々 TenantRegion に格納されていたのでフィールドを追加していません。

2022-05-25 08:07 UTC, ysssasaki approved these changes

2022-05-25 08:24 UTC, merged